name: Blog - Alexander van Rossum
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9407404859084636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b0000'
    - '#ffffff'
    - '#dfafaf'
    - '#b44141'
    - '#c36666'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
